FROM continuumio/miniconda3:4.10.3

RUN conda update conda -y

RUN apt update && apt install -y -q git alien tabix pigz gzip zlibc zlib1g-dev zlib1g xkcdpass vim p7zip-full parallel rsync curl
RUN conda config --add channels conda-forge
RUN conda config --add channels bioconda
RUN conda install -y pip mamba
RUN mamba install -y pandas xlrd ea-utils configparser requests illumina-interop gh openpyxl 
RUN mamba install -y snakemake=7.15.2 singularity=3.8.5
RUN mamba update numpy

#Allow shared loop devices for singularity
RUN sed -i -e 's/shared loop devices = no/shared loop devices = yes/g' /opt/conda/etc/singularity/singularity.conf

WORKDIR /opt

RUN mkdir images
COPY files/ntnu.png images/
COPY files/logo_ntnu.png /opt/images/

ENV BCL2FASTQ_VERSION=2.20.0.422
COPY files/bcl2fastq2-v$BCL2FASTQ_VERSION-Linux-x86_64.rpm /tmp
RUN alien -i /tmp/bcl2fastq2-v$BCL2FASTQ_VERSION-Linux-x86_64.rpm

ENV BCL_CONVERT_VERSION=4.0.3
COPY files/bcl-convert-$BCL_CONVERT_VERSION-2.el7.x86_64.rpm /tmp
RUN alien -i /tmp/bcl-convert-$BCL_CONVERT_VERSION-2.el7.x86_64.rpm

RUN mkdir /bfq
WORKDIR /bfq
RUN mkdir output seq_share data log

WORKDIR /opt

ENV CR_VERSION=7.2.0
COPY files/cellranger-$CR_VERSION.tar.gz /tmp/cellranger-$CR_VERSION.tar.gz
RUN tar -C /opt/ -zxvf /tmp/cellranger-$CR_VERSION.tar.gz
ENV PATH=$PATH:/opt/cellranger-$CR_VERSION
RUN rm /tmp/cellranger-$CR_VERSION.tar.gz

COPY files/cellranger-atac-1.2.0.tar.gz /tmp/cellranger-atac-1.2.0.tar.gz
RUN tar -C /opt/ -xvf /tmp/cellranger-atac-1.2.0.tar.gz
ENV PATH=$PATH:/opt/cellranger-atac-1.2.0
RUN rm /tmp/cellranger-atac-1.2.0.tar.gz

COPY files/spaceranger-1.2.1.tar.gz /tmp/spaceranger-1.2.1.tar.gz
RUN tar -C /opt/ -xvf /tmp/spaceranger-1.2.1.tar.gz
ENV PATH=$PATH:/opt/spaceranger-1.2.1
RUN rm /tmp/spaceranger-1.2.1.tar.gz

#FIX for qiime2 cli: need access to cache files in /home of q2 image
RUN chmod -R a+w /home

ENV TMPDIR=/bfq-tmp
ENV EXT_DIR=/bfq-ext
ENV GCF_EXT=$EXT_DIR
ENV SINGULARITY_BINDPATH=/mnt,/opt/gcf-workflows,/bfq-tmp,/bfq-ext,/home
ENV SINGULARITY_CACHEDIR=$TMPDIR/singularity/
ENV SINGULARITY_TMPDIR=$SINGULARITY_CACHEDIR/tmp
ENV SINGULARITY_LOCALCACHEDIR=$SINGULARITY_CACHEDIR/tmp/
ENV SINGULARITY_PULLFOLDER=$SINGULARITY_CACHEDIR
ENV GCF_SECRET=/secrets/gcf_secrets.yaml

ENV FORCE_BCL2FASTQ=True
