FROM gcfntnu/bfq:base-260925

ENV BFQ_ENV=production

ADD https://api.github.com/repos/gcfntnu/gcf-tools/git/refs/heads/master conf_version
RUN /opt/conda/bin/python -m pip install --upgrade https://github.com/gcfntnu/gcf-tools/archive/master.zip && \
    /opt/conda/bin/python -c "from configmaker.validation import VALIDATION_API_VERSION; assert VALIDATION_API_VERSION == 1"

ADD https://api.github.com/repos/gcfntnu/gcf-bfq/git/refs/heads/master gcf-bfq_version
RUN git clone https://github.com/gcfntnu/gcf-bfq.git /opt/gcf-bfq && \
    cd /opt/gcf-bfq && \
    git checkout master && \
    /opt/conda/bin/python -m pip install . && /opt/conda/bin/python -m pip check

ADD https://api.github.com/repos/gcfntnu/gcf-workflows/git/refs/heads/main gcf-workflows_version
RUN cd /opt && git clone https://github.com/gcfntnu/gcf-workflows.git && cd /opt/gcf-workflows && git checkout main

WORKDIR /opt
CMD ["bfq"]
