FROM gcfntnu/bfq:base-260925

ENV BFQ_ENV=test

ARG GCF_TOOLS_BRANCH=bfq-dev
ADD https://api.github.com/repos/gcfntnu/gcf-tools/git/refs/heads/$GCF_TOOLS_BRANCH conf_version
# BFQ and its configmaker subprocess must resolve the same validation API.
RUN /opt/conda/bin/python -m pip install --upgrade https://github.com/gcfntnu/gcf-tools/archive/$GCF_TOOLS_BRANCH.zip && \
    /opt/conda/bin/python -c "from configmaker.validation import VALIDATION_API_VERSION; assert VALIDATION_API_VERSION == 1"

ARG GCF_WORKFLOWS_BRANCH=bfq-dev
ADD https://api.github.com/repos/gcfntnu/gcf-workflows/git/refs/heads/$GCF_WORKFLOWS_BRANCH gcf-workflows_version
RUN cd /opt && git clone https://github.com/gcfntnu/gcf-workflows.git && cd /opt/gcf-workflows && git checkout $GCF_WORKFLOWS_BRANCH

COPY pyproject.toml /opt/gcf-bfq/pyproject.toml
COPY bcl2fastq_pipeline /opt/gcf-bfq/bcl2fastq_pipeline
RUN /opt/conda/bin/python -m pip install /opt/gcf-bfq && /opt/conda/bin/python -m pip check

WORKDIR /opt
CMD ["bfq"]
