FROM gcfntnu/bfq:base

ADD https://api.github.com/repos/gcfntnu/gcf-tools/git/refs/heads/master conf_version
RUN pip install https://github.com/gcfntnu/gcf-tools/archive/master.zip

ADD https://api.github.com/repos/gcfntnu/MultiQC/git/refs/heads/master multiqc_version
RUN pip install https://github.com/gcfntnu/MultiQC/archive/master.zip 

ADD https://api.github.com/repos/gcfntnu/gcf-bfq/git/refs/heads/master gcf-bfq_version
RUN cd /tmp && git clone https://github.com/gcfntnu/gcf-bfq.git && cd /tmp/gcf-bfq && git checkout master && cp -r /tmp/gcf-bfq/bcl2fastq_pipeline /opt
ENV PATH=$PATH:/opt/bcl2fastq_pipeline/flowcell_manager

ADD https://api.github.com/repos/gcfntnu/gcf-workflows/git/refs/heads/main gcf-workflows_version
RUN cd /opt && git clone https://github.com/gcfntnu/gcf-workflows.git && cd /opt/gcf-workflows && git checkout main

WORKDIR /opt/bcl2fastq_pipeline
RUN gcc splitFastq.c -o splitFastq
RUN ./setup.py build
RUN ./setup.py install

ENV PATH=$PATH:/opt/bcl2fastq_pipeline

ADD ./files/mqc_headers /opt/mqc_headers

ENV PATH=$PATH:/opt/bcl2fastq_pipeline
CMD bin/bfq.py
