FROM gcfntnu/bfq:base

ARG GCF_TOOLS_BRANCH=bfq-dev
ADD https://api.github.com/repos/gcfntnu/gcf-tools/git/refs/heads/$GCF_TOOLS_BRANCH conf_version
RUN pip install https://github.com/gcfntnu/gcf-tools/archive/$GCF_TOOLS_BRANCH.zip

ARG MULTIQC_BRANCH=bfq-dev
ADD https://api.github.com/repos/gcfntnu/MultiQC/git/refs/heads/$MULTIQC_BRANCH multiqc_version
RUN pip install https://github.com/gcfntnu/MultiQC/archive/$MULTIQC_BRANCH.zip 

ARG GCF_WORKFLOWS_BRANCH=bfq-dev
ADD https://api.github.com/repos/gcfntnu/gcf-workflows/git/refs/heads/$GCF_WORKFLOWS_BRANCH gcf-workflows_version
RUN cd /opt && git clone https://github.com/gcfntnu/gcf-workflows.git && cd /opt/gcf-workflows && git checkout $GCF_WORKFLOWS_BRANCH

COPY ./bcl2fastq_pipeline /opt/bcl2fastq_pipeline
ENV PATH=$PATH:/opt/bcl2fastq_pipeline/flowcell_manager
WORKDIR /opt/bcl2fastq_pipeline
RUN gcc splitFastq.c -o splitFastq
RUN ./setup.py build
RUN ./setup.py install

ENV PATH=$PATH:/opt/bcl2fastq_pipeline

ADD ./files/snakefiles /opt/snakefiles
ADD ./files/qiaseq /opt/qiaseq
ADD ./files/mqc_headers /opt/mqc_headers

ENV PATH=$PATH:/opt/bcl2fastq_pipeline
CMD bin/bfq.py
